spring:
  datasource:
    hikari:
      pool-name: hikariPool
      transaction-isolation: TRANSACTION_READ_COMMITTED
      connection-timeout: 1000 #ms
      max-lifetime: 580000
      idle-timeout: 0
      maximum-pool-size: 20
      minimum-idle: 20

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect.storage_engine: innodb

server:
  port: 5000
  tomcat:
    max-threads: 256
    accept-count: 1000