### 회원 가입
POST http://localhost:5000/members
Content-Type: application/json

{
  "userId": "kim",
  "password": "1234"
}


### 로그인
POST http://localhost:5000/login
Content-Type: application/json

{
  "userId": "kim",
  "password": "1234"
}


### 로그아웃
POST http://localhost:5000/logout
Content-Type: application/json


### 로그인 여부 확인
GET http://localhost:5000/members/1/login
Content-Type: application/json

###